name: Build

on:
  push:
  pull_request:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Build project
        run: ./mvnw -B -DskipTests package
